apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-alert
    receivers:
      - uid: discord-alert-receiver
        type: discord
        settings:
          url: "REPLACE_WITH_YOUR_DISCORD_WEBHOOK_URL"
          use_discord_username: true
